apiVersion: v2
name: azure-vote-front
description: A Helm chart for Kubernetes

dependencies:
  - name: redis
    version: 16.12.2
    repository: https://charts.bitnami.com/bitnami
    
type: application
version: 0.1.0
appVersion: "1.16.0"
