name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    name: Build App
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.DOCKER_PAT }}
    
    - name: Build and Push Image
      uses: docker/build-push-action@v2
      with:
          context: .
          file: azure-vote/Dockerfile
          push: true
          tags: |
            ghcr.io/canarysplayground/voting-app:latest
            ghcr.io/canarysplayground/voting-app:${{ steps.date.outputs.date }}.${{ github.run_number }}
